In [1]:
import pandas as pd

In [2]:
# trip count for every company from 15th to 16th November 2017
company_count_df = pd.read_csv('data/project_sql_result_01.csv')

# average trips per day that ended in every neighbourhood in November
dropoff_count_df = pd.read_csv('data/project_sql_result_04.csv')

# weather conditions and trip duration for trips from Loop to O'Hare Airport
weather_df = pd.read_csv('data/project_sql_result_07.csv')

### 1 - Cleaning

#### 1.1 - company_count_df

In [3]:
company_count_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   company_name  64 non-null     str
 1   trips_amount  64 non-null     int64
dtypes: int64(1), str(1)
memory usage: 1.1 KB

In [4]:
company_count_df['company_name'] = (company_count_df['company_name']
                                    .str.lower()
                                    .str.strip()
)

In [5]:
# check for duplicated company names
company_count_df[company_count_df['company_name'].duplicated()]

Empty DataFrame
Columns: [company_name, trips_amount]
Index: []

There are 64 company names and there is no duplicated value.

#### 1.2 - dropoff_count_df

In [6]:
dropoff_count_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dropoff_location_name  94 non-null     str
 1   average_trips          94 non-null     float64
dtypes: float64(1), str(1)
memory usage: 1.6 KB

In [8]:
dropoff_count_df['dropoff_location_name'] = (
    dropoff_count_df['dropoff_location_name']
    .str.lower()
    .str.strip()
)

In [10]:
dropoff_count_df[dropoff_count_df['dropoff_location_name'].duplicated()]

Empty DataFrame
Columns: [dropoff_location_name, average_trips]
Index: []

There are 94 dropoff locations and there is no duplicated value.

#### 1.3 - weather_df

In [20]:
weather_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1068 entries, 0 to 1067
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   start_ts            1068 non-null   datetime64[us]
 1   weather_conditions  1068 non-null   str
 2   duration_seconds    1068 non-null   float64
dtypes: datetime64[us](1), float64(1), str(1)
memory usage: 25.2 KB

In [19]:
weather_df.head()

             start_ts weather_conditions  duration_seconds
0 2017-11-25 16:00:00               Good            2410.0
1 2017-11-25 14:00:00               Good            1920.0
2 2017-11-25 12:00:00               Good            1543.0
3 2017-11-04 10:00:00               Good            2512.0
4 2017-11-11 07:00:00               Good            1440.0

start_df is in string DataType, it should be DateTime.

In [18]:
weather_df['start_ts'] = pd.to_datetime(weather_df['start_ts'],
                                        format='%Y-%m-%d %H:%M:%S'
)

In [23]:
weather_df['weather_conditions'] = (weather_df['weather_conditions']
                                    .str.lower()
                                    .str.strip()
)

In [22]:
dropoff_count_df[dropoff_count_df.duplicated()]

Empty DataFrame
Columns: [dropoff_location_name, average_trips]
Index: []

In [ ]:
# Verify low duration trips
weather_df.sort_values('duration_seconds').head()

                start_ts weather_conditions  duration_seconds
163  2017-11-11 09:00:00               good               0.0
168  2017-11-11 07:00:00               good               0.0
1063 2017-11-25 11:00:00               good               0.0
204  2017-11-18 19:00:00               good               0.0
552  2017-11-04 01:00:00               good               0.0

In [ ]:
weather_df[weather_df['duration_seconds'] < 60]

                start_ts weather_conditions  duration_seconds
163  2017-11-11 09:00:00               good               0.0
168  2017-11-11 07:00:00               good               0.0
204  2017-11-18 19:00:00               good               0.0
552  2017-11-04 01:00:00               good               0.0
801  2017-11-04 09:00:00               good               0.0
1063 2017-11-25 11:00:00               good               0.0

start_df was changed to DateTyme. There is no duplicated rows. There are 6
trips with 0 seconds duration that can be cancelled trips